// QUIZ CARDS — multi-language
// mnemonic_vi / _th / _zh / _ru / _lo / _km
// examples: each has word + translations

export const QUIZ_CARDS = [
  { id:"p-anti", affix:"anti-", type:"prefix", color:"#EF5350",
    meaning:"against, opposing",
    translations:{ vi:"chống lại, phản đối", th:"ต่อต้าน", zh:"反对，对抗", ru:"против, антагонизм", lo:"ຕ້ານ", km:"ប្រឆាំងនឹង" },
    examples:[{ word:"antibiotics", vi:"kháng sinh", th:"ยาปฏิชีวนะ", zh:"抗生素", ru:"антибиотики", lo:"ຢາຕ້ານເຊື້ອ", km:"ថ្នាំប្រឆាំងមេរោគ" }, { word:"antiwar", vi:"phản chiến", th:"ต่อต้านสงคราม", zh:"反战", ru:"антивоенный", lo:"ຕ້ານສົງຄາມ", km:"ប្រឆាំងសង្គ្រាម" }, { word:"antisocial", vi:"chống xã hội", th:"ต่อต้านสังคม", zh:"反社会", ru:"антисоциальный", lo:"ຕ້ານສັງຄົມ", km:"ប្រឆាំងសង្គម" }],
    mnemonic:{ vi:"ANTI = chống lại, luôn phản đối!", th:"ANTI = ต่อต้าน เช่น antiwar!", zh:"ANTI = 反对，如 antiwar!", ru:"ANTI = против, как антивирус!", lo:"ANTI = ຕ້ານ ເຊັ່ນ antiwar!", km:"ANTI = ប្រឆាំង ដូច antiwar!" }},
  { id:"p-auto", affix:"auto-", type:"prefix", color:"#7E57C2",
    meaning:"self, by oneself",
    translations:{ vi:"tự, bản thân", th:"ตนเอง, อัตโนมัติ", zh:"自己，自动", ru:"сам, автоматически", lo:"ຕົນເອງ, ອັດຕະໂນມັດ", km:"ខ្លួនឯង ស្វ័យ" },
    examples:[{ word:"autobiography", vi:"tự truyện", th:"อัตชีวประวัติ", zh:"自传", ru:"автобиография", lo:"ຊີວະປະຫວັດຕົນເອງ", km:"ជីវប្រវត្តិខ្លួនឯង" }, { word:"automatic", vi:"tự động", th:"อัตโนมัติ", zh:"自动的", ru:"автоматический", lo:"ອັດຕະໂນມັດ", km:"ស្វ័យប្រវត្តិ" }, { word:"automobile", vi:"ô tô", th:"รถยนต์", zh:"汽车", ru:"автомобиль", lo:"ລົດຍົນ", km:"រថយន្ត" }],
    mnemonic:{ vi:"AUTO = tự lái xe, không cần người khác!", th:"AUTO = อัตโนมัติ ทำเองได้!", zh:"AUTO = 自动，无需他人!", ru:"AUTO = сам, как автопилот!", lo:"AUTO = ຕົນເອງ ບໍ່ຕ້ອງການຄົນອື່ນ!", km:"AUTO = ខ្លួនឯង គ្មានអ្នកជំនួយ!" }},
  { id:"p-de", affix:"de-", type:"prefix", color:"#FF7043",
    meaning:"undo, remove, reduce",
    translations:{ vi:"làm ngược lại, tháo ra, giảm", th:"ย้อนกลับ, ลด", zh:"撤销，减少", ru:"отменить, снять", lo:"ຖອດ, ຫຼຸດ", km:"លុបចោល កាត់" },
    examples:[{ word:"decode", vi:"giải mã", th:"ถอดรหัส", zh:"解码", ru:"декодировать", lo:"ຖອດລະຫັດ", km:"ឌីខូដ" }, { word:"deflate", vi:"xả hơi", th:"ปล่อยลม", zh:"放气", ru:"сдуть", lo:"ຫຼຸດ", km:"ដក" }, { word:"dehydrate", vi:"khử nước", th:"ขาดน้ำ", zh:"脱水", ru:"обезвоживать", lo:"ຂາດນ້ຳ", km:"ខ្វះទឹក" }],
    mnemonic:{ vi:"DE- = tháo ra, giải mã như debug!", th:"DE- = ย้อนกลับ เช่น decode!", zh:"DE- = 撤销，如 decode!", ru:"DE- = снять, как дефрагментация!", lo:"DE- = ຖອດ ເຊັ່ນ decode!", km:"DE- = លុប ដូច decode!" }},
  { id:"p-dis", affix:"dis-", type:"prefix", color:"#EF5350",
    meaning:"not, opposite, away",
    translations:{ vi:"không, ngược lại, xa", th:"ไม่, ตรงข้าม", zh:"不，相反", ru:"не, противоположность", lo:"ບໍ່, ກົງກັນຂ້າມ", km:"មិន ផ្ទុយ" },
    examples:[{ word:"disagree", vi:"không đồng ý", th:"ไม่เห็นด้วย", zh:"不同意", ru:"не соглашаться", lo:"ບໍ່ເຫັນດ້ວຍ", km:"មិនយល់ព្រម" }, { word:"dishonest", vi:"không trung thực", th:"ไม่ซื่อสัตย์", zh:"不诚实", ru:"нечестный", lo:"ບໍ່ຊື່ສັດ", km:"មិនស្មោះត្រង់" }, { word:"disappear", vi:"biến mất", th:"หายไป", zh:"消失", ru:"исчезать", lo:"ຫາຍໄປ", km:"បាត់ទៅ" }],
    mnemonic:{ vi:"DIS- = dislike, không thích, phủ định!", th:"DIS- = disappear หายไปเลย!", zh:"DIS- = disappear，消失!", ru:"DIS- = disagree, не согласен!", lo:"DIS- = disappear ຫາຍໄປ!", km:"DIS- = disappear បាត់!" }},
  { id:"p-ex", affix:"ex-", type:"prefix", color:"#FFA726",
    meaning:"out of, former",
    translations:{ vi:"ra ngoài, cũ, trước đây", th:"ออกไป, อดีต", zh:"出去，前", ru:"наружу, бывший", lo:"ອອກ, ເກົ່າ", km:"ចេញ អតីត" },
    examples:[{ word:"export", vi:"xuất khẩu", th:"ส่งออก", zh:"出口", ru:"экспорт", lo:"ສົ່ງອອກ", km:"នាំចេញ" }, { word:"exhale", vi:"thở ra", th:"หายใจออก", zh:"呼气", ru:"выдыхать", lo:"ຫາຍໃຈອອກ", km:"ដកដង្ហើមចេញ" }, { word:"extract", vi:"chiết xuất", th:"สกัด", zh:"提取", ru:"извлечь", lo:"ສະກັດ", km:"ស្រង់" }],
    mnemonic:{ vi:"EX- = ra ngoài, như exit!", th:"EX- = exit ออกไปเลย!", zh:"EX- = exit，出去!", ru:"EX- = exit, наружу!", lo:"EX- = exit ອອກ!", km:"EX- = exit ចេញ!" }},
  { id:"p-inter", affix:"inter-", type:"prefix", color:"#29B6F6",
    meaning:"between, among",
    translations:{ vi:"giữa, trong số", th:"ระหว่าง, ในหมู่", zh:"之间，在...中间", ru:"между, среди", lo:"ລະຫວ່າງ, ໃນ", km:"ចន្លោះ ក្នុងចំណោម" },
    examples:[{ word:"international", vi:"quốc tế", th:"นานาชาติ", zh:"国际的", ru:"международный", lo:"ສາກົນ", km:"អន្តរជាតិ" }, { word:"interact", vi:"tương tác", th:"โต้ตอบ", zh:"互动", ru:"взаимодействовать", lo:"ໂຕ້ຕອບ", km:"អន្តរកម្ម" }, { word:"internet", vi:"internet", th:"อินเทอร์เน็ต", zh:"互联网", ru:"интернет", lo:"ອິນເຕີເນັດ", km:"អ៊ីនធឺណែត" }],
    mnemonic:{ vi:"INTER = internet, kết nối GIUA cac thiet bi!", th:"INTER = internet เชื่อมต่อระหว่างกัน!", zh:"INTER = internet，连接之间!", ru:"INTER = интернет, между сетями!", lo:"INTER = internet ເຊື່ອມໂຍງ!", km:"INTER = internet ភ្ជាប់!" }},
  { id:"p-mis", affix:"mis-", type:"prefix", color:"#FF7043",
    meaning:"wrongly, badly",
    translations:{ vi:"sai, lầm lẫn", th:"ผิด, ไม่ถูก", zh:"错误地，不好地", ru:"неправильно, плохо", lo:"ຜິດ, ບໍ່ຖືກ", km:"ខុស ឆ្គង" },
    examples:[{ word:"misunderstand", vi:"hiểu lầm", th:"เข้าใจผิด", zh:"误解", ru:"неправильно понять", lo:"ເຂົ້າໃຈຜິດ", km:"យល់ខុស" }, { word:"mispronounce", vi:"phát âm sai", th:"ออกเสียงผิด", zh:"发音错误", ru:"неправильно произносить", lo:"ອອກສຽງຜິດ", km:"សំដែងខុស" }, { word:"mistake", vi:"sai lầm", th:"ความผิดพลาด", zh:"错误", ru:"ошибка", lo:"ຄວາມຜິດ", km:"កំហុស" }],
    mnemonic:{ vi:"MIS- = mistake, lam sai!", th:"MIS- = mistake ทำผิด!", zh:"MIS- = mistake，做错!", ru:"MIS- = mistake, ошибка!", lo:"MIS- = mistake ຜິດ!", km:"MIS- = mistake ខុស!" }},
  { id:"p-over", affix:"over-", type:"prefix", color:"#AB47BC",
    meaning:"too much, above",
    translations:{ vi:"quá nhiều, phía trên", th:"มากเกินไป, เหนือ", zh:"过多，在上方", ru:"слишком много, сверху", lo:"ຫຼາຍເກີນໄປ, ເທິງ", km:"ច្រើនពេក លើ" },
    examples:[{ word:"overflow", vi:"tràn đầy", th:"ล้น", zh:"溢出", ru:"переполнять", lo:"ລົ້ນ", km:"넘 overflow" }, { word:"overwork", vi:"làm việc quá sức", th:"ทำงานหนักเกิน", zh:"过度工作", ru:"перерабатывать", lo:"ເຮັດວຽກຫຼາຍເກີນ", km:"ធ្វើការច្រើនពេក" }, { word:"overcome", vi:"vượt qua", th:"เอาชนะ", zh:"克服", ru:"преодолевать", lo:"ເອົາຊະນະ", km:"ឈ្នះ" }],
    mnemonic:{ vi:"OVER = qua nhieu, game over!", th:"OVER = game over เกินขีดจำกัด!", zh:"OVER = game over，超过限制!", ru:"OVER = перебор, как game over!", lo:"OVER = game over ເກີນ!", km:"OVER = game over លើស!" }},
  { id:"p-pre", affix:"pre-", type:"prefix", color:"#42A5F5",
    meaning:"before, in advance",
    translations:{ vi:"trước, sẵn trước", th:"ก่อน, ล่วงหน้า", zh:"之前，提前", ru:"до, заранее", lo:"ກ່ອນ, ລ່ວງໜ້າ", km:"មុន ទុកជាមុន" },
    examples:[{ word:"preview", vi:"xem trước", th:"ตัวอย่าง", zh:"预览", ru:"предварительный просмотр", lo:"ເບິ່ງລ່ວງໜ້າ", km:"ព្រីវ្យូ" }, { word:"predict", vi:"dự đoán", th:"ทำนาย", zh:"预测", ru:"предсказывать", lo:"ທຳນາຍ", km:"ព្យាករណ៍" }, { word:"prepare", vi:"chuẩn bị", th:"เตรียม", zh:"准备", ru:"готовиться", lo:"ກຽມຕົວ", km:"ត្រៀម" }],
    mnemonic:{ vi:"PRE = preview, xem TRUOC khi chieu!", th:"PRE = preview ดูก่อนฉาย!", zh:"PRE = preview，放映前先看!", ru:"PRE = preview, сначала!", lo:"PRE = preview ເບິ່ງກ່ອນ!", km:"PRE = preview មើលមុន!" }},
  { id:"p-re", affix:"re-", type:"prefix", color:"#26C6DA",
    meaning:"again, back",
    translations:{ vi:"lại, quay lại", th:"อีกครั้ง, กลับ", zh:"再次，回", ru:"снова, назад", lo:"ອີກ, ກັບ", km:"ម្តងទៀត ត្រលប់" },
    examples:[{ word:"replay", vi:"phát lại", th:"เล่นซ้ำ", zh:"重播", ru:"воспроизводить снова", lo:"ຫຼິ້ນຄືນ", km:"ចាក់ម្តងទៀត" }, { word:"return", vi:"quay lại", th:"กลับ", zh:"返回", ru:"возвращаться", lo:"ກັບຄືນ", km:"ត្រលប់" }, { word:"rebuild", vi:"xây dựng lại", th:"สร้างใหม่", zh:"重建", ru:"перестраивать", lo:"ສ້າງໃໝ່", km:"កសាងឡើងវិញ" }],
    mnemonic:{ vi:"RE = replay, lam LAI tu dau!", th:"RE = replay ทำอีกครั้ง!", zh:"RE = replay，重来一次!", ru:"RE = replay, начать снова!", lo:"RE = replay ຫຼິ້ນຄືນ!", km:"RE = replay ម្តងទៀត!" }},
  { id:"p-sub", affix:"sub-", type:"prefix", color:"#5C6BC0",
    meaning:"under, below",
    translations:{ vi:"dưới, bên dưới", th:"ใต้, ข้างล่าง", zh:"在下面，低于", ru:"под, ниже", lo:"ລ່ຽມ, ຂ້າງລຸ່ມ", km:"ក្រោម ខាងក្រោម" },
    examples:[{ word:"submarine", vi:"tàu ngầm", th:"เรือดำน้ำ", zh:"潜水艇", ru:"подводная лодка", lo:"ເຮືອດຳນ້ຳ", km:"នាវាមុជទឹក" }, { word:"subway", vi:"tàu điện ngầm", th:"รถไฟใต้ดิน", zh:"地铁", ru:"метро", lo:"ລົດໄຟໃຕ້ດິນ", km:"រថភ្លើងក្រោមដី" }, { word:"subtitle", vi:"phụ đề", th:"คำบรรยาย", zh:"字幕", ru:"субтитры", lo:"ຄຳບັນຍາຍ", km:"ចំណងជើងរង" }],
    mnemonic:{ vi:"SUB = submarine, luon o DUOI nuoc!", th:"SUB = submarine อยู่ใต้น้ำ!", zh:"SUB = submarine，在水下!", ru:"SUB = submarine, под водой!", lo:"SUB = submarine ຢູ່ໃຕ້ນ້ຳ!", km:"SUB = submarine នៅក្រោមទឹក!" }},
  { id:"p-super", affix:"super-", type:"prefix", color:"#FFCA28",
    meaning:"above, beyond, more than",
    translations:{ vi:"siêu, vượt trội, hơn", th:"เหนือกว่า, ยอดเยี่ยม", zh:"超，在...之上", ru:"сверх, выше", lo:"ເໜືອ, ດີເລີດ", km:"ហួស លើ" },
    examples:[{ word:"superhero", vi:"siêu anh hùng", th:"ซูเปอร์ฮีโร่", zh:"超级英雄", ru:"супергерой", lo:"ຊຸບເປີຮີໂຣ", km:"វីរបុរសសម្ភារ" }, { word:"supernatural", vi:"siêu nhiên", th:"เหนือธรรมชาติ", zh:"超自然", ru:"сверхъестественный", lo:"ເໜືອທຳມະຊາດ", km:"ហួសធម្មជាតិ" }, { word:"supermarket", vi:"siêu thị", th:"ซูเปอร์มาร์เก็ต", zh:"超市", ru:"супермаркет", lo:"ຕະຫຼາດຊຸບ", km:"ផ្សារទំនើប" }],
    mnemonic:{ vi:"SUPER = sieu nhan, vuot ra ngoai binh thuong!", th:"SUPER = ซูเปอร์ฮีโร่ เกินกว่าปกติ!", zh:"SUPER = 超级英雄，超越普通!", ru:"SUPER = супергерой, сверх нормы!", lo:"SUPER = ຊຸບເປີ ເໜືອທຳດາ!", km:"SUPER = ហួស សម្ភារ!" }},
  { id:"p-tele", affix:"tele-", type:"prefix", color:"#26A69A",
    meaning:"far, distant",
    translations:{ vi:"xa, từ xa", th:"ไกล, ระยะไกล", zh:"远，从远处", ru:"далеко, издалека", lo:"ໄກ, ຈາກໄກ", km:"ឆ្ងាយ ពីចម្ងាយ" },
    examples:[{ word:"telephone", vi:"điện thoại", th:"โทรศัพท์", zh:"电话", ru:"телефон", lo:"ໂທລະສັບ", km:"ទូរស័ព្ទ" }, { word:"television", vi:"truyền hình", th:"โทรทัศน์", zh:"电视", ru:"телевидение", lo:"ໂທລະທັດ", km:"ទូរទស្សន៍" }, { word:"telescope", vi:"kính thiên văn", th:"กล้องโทรทรรศน์", zh:"望远镜", ru:"телескоп", lo:"ກ້ອງສ່ອງທາງໄກ", km:"កែវយឺតហ្លើង" }],
    mnemonic:{ vi:"TELE = telephone, goi tu rat XA!", th:"TELE = telephone โทรจากไกล!", zh:"TELE = telephone，从远处打电话!", ru:"TELE = telephone, звонок издалека!", lo:"TELE = telephone ໂທຈາກໄກ!", km:"TELE = telephone ហៅពីចម្ងាយ!" }},
  { id:"p-trans", affix:"trans-", type:"prefix", color:"#EF5350",
    meaning:"across, through, beyond",
    translations:{ vi:"qua, xuyên qua", th:"ข้าม, ผ่าน", zh:"穿越，跨越", ru:"через, поперёк", lo:"ຂ້າມ, ຜ່ານ", km:"ឆ្លង ឆ្ពោះ" },
    examples:[{ word:"transport", vi:"vận chuyển", th:"ขนส่ง", zh:"运输", ru:"транспорт", lo:"ຂົນສົ່ງ", km:"ដឹកជញ្ជូន" }, { word:"translate", vi:"dịch", th:"แปล", zh:"翻译", ru:"переводить", lo:"ແປ", km:"បកប្រែ" }, { word:"transfer", vi:"chuyển nhượng", th:"โอน", zh:"转让", ru:"передавать", lo:"ໂອນ", km:"ផ្ទេរ" }],
    mnemonic:{ vi:"TRANS = transport, vuot qua de den ben kia!", th:"TRANS = transport ข้ามไปอีกฝั่ง!", zh:"TRANS = transport，越过到另一边!", ru:"TRANS = транспорт, пересекает!", lo:"TRANS = transport ຂ້າມໄປ!", km:"TRANS = transport ឆ្ពោះ!" }},
  { id:"p-un", affix:"un-", type:"prefix", color:"#EC407A",
    meaning:"not, reverse",
    translations:{ vi:"không, phủ định, đảo ngược", th:"ไม่, ตรงข้าม", zh:"不，相反", ru:"не, обратное", lo:"ບໍ່, ກົງກັນຂ້າມ", km:"មិន ផ្ទុយ" },
    examples:[{ word:"unhappy", vi:"không hạnh phúc", th:"ไม่มีความสุข", zh:"不快乐", ru:"несчастный", lo:"ບໍ່ສຸກ", km:"មិនសប្បាយ" }, { word:"unlock", vi:"mở khóa", th:"ปลดล็อก", zh:"解锁", ru:"разблокировать", lo:"ປົດລ໋ອກ", km:"ដោះ" }, { word:"unusual", vi:"khác thường", th:"ผิดปกติ", zh:"不寻常", ru:"необычный", lo:"ຜິດປົກກະຕິ", km:"មិនធម្មតា" }],
    mnemonic:{ vi:"UN- = undo button, xoa bo, nguoc lai!", th:"UN- = undo ยกเลิก!", zh:"UN- = undo，取消!", ru:"UN- = undo, отмена!", lo:"UN- = undo ຍົກເລີກ!", km:"UN- = undo លុប!" }},

  // SUFFIXES
  { id:"s-able", affix:"-able / -ible", type:"suffix", color:"#66BB6A",
    meaning:"able to, capable of",
    translations:{ vi:"có thể, có khả năng", th:"สามารถ, มีความสามารถ", zh:"能够，有能力", ru:"способный, можно", lo:"ສາມາດ", km:"អាច មានសមត្ថភាព" },
    examples:[{ word:"readable", vi:"có thể đọc được", th:"อ่านได้", zh:"可读的", ru:"читаемый", lo:"ອ່ານໄດ້", km:"អានបាន" }, { word:"flexible", vi:"linh hoạt", th:"ยืดหยุ่น", zh:"灵活的", ru:"гибкий", lo:"ຫຍຸ້ນ", km:"រហ័ស" }, { word:"comfortable", vi:"thoải mái", th:"สบาย", zh:"舒适", ru:"удобный", lo:"ສະດວກ", km:"ស្រួល" }],
    mnemonic:{ vi:"-ABLE = capable, CO KHA NANG lam dieu do!", th:"-ABLE = capable สามารถทำได้!", zh:"-ABLE = capable，有能力做到!", ru:"-ABLE = способный, могу сделать!", lo:"-ABLE = capable ສາມາດ!", km:"-ABLE = capable អាច!" }},
  { id:"s-ation", affix:"-ation / -tion", type:"suffix", color:"#FFA726",
    meaning:"act of, process, state",
    translations:{ vi:"hành động, quá trình, trạng thái", th:"การกระทำ, กระบวนการ", zh:"行为，过程，状态", ru:"действие, процесс", lo:"ການກະທຳ, ຂະບວນການ", km:"ដំណើរការ ស្ថានភាព" },
    examples:[{ word:"education", vi:"giáo dục", th:"การศึกษา", zh:"教育", ru:"образование", lo:"ການສຶກສາ", km:"ការអប់រំ" }, { word:"communication", vi:"giao tiếp", th:"การสื่อสาร", zh:"交流", ru:"коммуникация", lo:"ການສື່ສານ", km:"ការទំនាក់ទំនង" }, { word:"foundation", vi:"nền tảng", th:"รากฐาน", zh:"基础", ru:"фундамент", lo:"ພື້ນຖານ", km:"មូលដ្ឋាន" }],
    mnemonic:{ vi:"-ATION bien dong tu thanh DANH TU!", th:"-ATION แปลงกริยาเป็นนาม!", zh:"-ATION 将动词变成名词!", ru:"-ATION превращает глагол в существительное!", lo:"-ATION ປ່ຽນ verb ເປັນ noun!", km:"-ATION ប្រែ verb ជា noun!" }},
  { id:"s-er", affix:"-er / -or", type:"suffix", color:"#29B6F6",
    meaning:"one who does, thing that does",
    translations:{ vi:"người làm, vật làm", th:"ผู้กระทำ, สิ่งที่ทำ", zh:"做...的人或物", ru:"тот, кто делает", lo:"ຜູ້ທີ່ເຮັດ", km:"អ្នកធ្វើ" },
    examples:[{ word:"teacher", vi:"giáo viên", th:"ครู", zh:"教师", ru:"учитель", lo:"ຄູ", km:"គ្រូ" }, { word:"actor", vi:"diễn viên", th:"นักแสดง", zh:"演员", ru:"актёр", lo:"ນັກສະແດງ", km:"តារាសម្តែង" }, { word:"computer", vi:"máy tính", th:"คอมพิวเตอร์", zh:"电脑", ru:"компьютер", lo:"ຄອມພິວເຕີ", km:"កុំព្យូទ័រ" }],
    mnemonic:{ vi:"-ER = worker, NGUOI hoac VAT thuc hien!", th:"-ER = worker ผู้ทำงาน!", zh:"-ER = worker，做事的人或物!", ru:"-ER = worker, тот кто работает!", lo:"-ER = worker ຜູ້ເຮັດ!", km:"-ER = worker អ្នកធ្វើ!" }},
  { id:"s-ful", affix:"-ful", type:"suffix", color:"#FFCA28",
    meaning:"full of, having",
    translations:{ vi:"đầy, có đặc tính", th:"เต็มไปด้วย, มี", zh:"充满，具有", ru:"полный, имеющий", lo:"ເຕັມ, ມີ", km:"ពោរពេញ មាន" },
    examples:[{ word:"beautiful", vi:"đẹp", th:"สวยงาม", zh:"美丽的", ru:"красивый", lo:"ສວຍງາມ", km:"ស្អាត" }, { word:"powerful", vi:"mạnh mẽ", th:"ทรงพลัง", zh:"强大的", ru:"мощный", lo:"ມີພະລັງ", km:"ខ្លាំង" }, { word:"thankful", vi:"biết ơn", th:"ขอบคุณ", zh:"感激的", ru:"благодарный", lo:"ຂອບໃຈ", km:"ដឹងគុណ" }],
    mnemonic:{ vi:"-FUL = full, DAY AP dac tinh do!", th:"-FUL = full เต็มไปด้วย!", zh:"-FUL = full，充满某种特质!", ru:"-FUL = полный чего-то!", lo:"-FUL = full ເຕັມ!", km:"-FUL = full ពោរពេញ!" }},
  { id:"s-less", affix:"-less", type:"suffix", color:"#EF5350",
    meaning:"without, lacking",
    translations:{ vi:"không có, thiếu", th:"ไม่มี, ขาด", zh:"没有，缺乏", ru:"без, лишён", lo:"ບໍ່ມີ, ຂາດ", km:"គ្មាន ខ្វះ" },
    examples:[{ word:"hopeless", vi:"vô vọng", th:"สิ้นหวัง", zh:"绝望的", ru:"безнадёжный", lo:"ສິ້ນຫວັງ", km:"អស់សង្ឃឹម" }, { word:"endless", vi:"vô tận", th:"ไม่มีสิ้นสุด", zh:"无尽的", ru:"бесконечный", lo:"ບໍ່ສິ້ນສຸດ", km:"គ្មានទីបញ្ចប់" }, { word:"fearless", vi:"vô úy", th:"ไม่กลัว", zh:"无畏的", ru:"бесстрашный", lo:"ບໍ່ຢ້ານ", km:"គ្មានការភ័យ" }],
    mnemonic:{ vi:"-LESS = homeless, KHONG CO, THIEU!", th:"-LESS = homeless ไม่มีบ้าน!", zh:"-LESS = homeless，没有!", ru:"-LESS = без дома, лишён!", lo:"-LESS = homeless ບໍ່ມີ!", km:"-LESS = homeless គ្មាន!" }},
  { id:"s-logy", affix:"-logy", type:"suffix", color:"#42A5F5",
    meaning:"study of, science of",
    translations:{ vi:"khoa học về, nghiên cứu về", th:"การศึกษาเกี่ยวกับ", zh:"...学，...科学", ru:"наука о, изучение", lo:"ການສຶກສາກ່ຽວກັບ", km:"ការសិក្សាអំពី" },
    examples:[{ word:"psychology", vi:"tâm lý học", th:"จิตวิทยา", zh:"心理学", ru:"психология", lo:"ຈິດຕະວິທະຍາ", km:"ចិត្តវិទ្យា" }, { word:"technology", vi:"công nghệ", th:"เทคโนโลยี", zh:"技术", ru:"технология", lo:"ເທັກໂນໂລຢີ", km:"បច្ចេកវិទ្យា" }, { word:"biology", vi:"sinh học", th:"ชีววิทยา", zh:"生物学", ru:"биология", lo:"ຊີວະວິທະຍາ", km:"ជីវវិទ្យា" }],
    mnemonic:{ vi:"-LOGY = biology, mon NGHIEN CUU ve chu de do!", th:"-LOGY = biology วิชาที่ศึกษา!", zh:"-LOGY = biology，研究某主题的学科!", ru:"-LOGY = биология, наука о чём-то!", lo:"-LOGY = biology ສຶກສາ!", km:"-LOGY = biology ការសិក្សា!" }},
  { id:"s-ly", affix:"-ly", type:"suffix", color:"#66BB6A",
    meaning:"in a manner of (adverb)",
    translations:{ vi:"theo cách, một cách (trạng từ)", th:"อย่าง (คำวิเศษณ์)", zh:"以...方式（副词）", ru:"по-..., образом (наречие)", lo:"ຢ່າງ (adverb)", km:"យ៉ាង (ក្រិយាវិសេសន៍)" },
    examples:[{ word:"quickly", vi:"một cách nhanh chóng", th:"อย่างรวดเร็ว", zh:"快速地", ru:"быстро", lo:"ຢ່າງວ່ອງໄວ", km:"លឿនៗ" }, { word:"carefully", vi:"một cách cẩn thận", th:"อย่างระมัดระวัง", zh:"仔细地", ru:"осторожно", lo:"ຢ່າງລະອຽດ", km:"ដោយប្រុងប្រយ័ត្ន" }, { word:"surprisingly", vi:"một cách ngạc nhiên", th:"อย่างน่าแปลกใจ", zh:"令人惊讶地", ru:"удивительно", lo:"ຢ່າງແປກໃຈ", km:"ដែលធ្វើឱ្យភ្ញាក់ផ្អើល" }],
    mnemonic:{ vi:"-LY bien tinh tu thanh TRANG TU!", th:"-LY แปลงคำคุณศัพท์เป็นกริยาวิเศษณ์!", zh:"-LY 将形容词变成副词!", ru:"-LY превращает прилагательное в наречие!", lo:"-LY ປ່ຽນ adjective ເປັນ adverb!", km:"-LY ប្រែ adjective ជា adverb!" }},
  { id:"s-ment", affix:"-ment", type:"suffix", color:"#FFA726",
    meaning:"action, process, result",
    translations:{ vi:"hành động, quá trình, kết quả", th:"การกระทำ, กระบวนการ", zh:"动作，过程，结果", ru:"действие, процесс", lo:"ການກະທຳ, ຜົນ", km:"ដំណើរការ លទ្ធផល" },
    examples:[{ word:"development", vi:"sự phát triển", th:"การพัฒนา", zh:"发展", ru:"развитие", lo:"ການພັດທະນາ", km:"ការអភិវឌ្ឍ" }, { word:"management", vi:"quản lý", th:"การจัดการ", zh:"管理", ru:"управление", lo:"ການຈັດການ", km:"ការគ្រប់គ្រង" }, { word:"achievement", vi:"thành tích", th:"ความสำเร็จ", zh:"成就", ru:"достижение", lo:"ຜົນສຳເລັດ", km:"ការបំពេញ" }],
    mnemonic:{ vi:"-MENT = government, bien dong tu thanh DANH TU!", th:"-MENT = government แปลงกริยาเป็นนาม!", zh:"-MENT = government，动词变名词!", ru:"-MENT = правительство, глагол в существительное!", lo:"-MENT = government verb ເປັນ noun!", km:"-MENT = government verb ជា noun!" }},
  { id:"s-ness", affix:"-ness", type:"suffix", color:"#EC407A",
    meaning:"state or condition of",
    translations:{ vi:"trạng thái, điều kiện", th:"สภาวะ, ลักษณะ", zh:"状态，条件", ru:"состояние, условие", lo:"ສະພາບ", km:"ស្ថានភាព លក្ខណៈ" },
    examples:[{ word:"happiness", vi:"hạnh phúc", th:"ความสุข", zh:"幸福", ru:"счастье", lo:"ຄວາມສຸກ", km:"សុភមង្គល" }, { word:"darkness", vi:"bóng tối", th:"ความมืด", zh:"黑暗", ru:"темнота", lo:"ຄວາມມືດ", km:"ភាពងងឹត" }, { word:"kindness", vi:"lòng tốt", th:"ความ親切", zh:"善良", ru:"доброта", lo:"ຄວາມໃຈດີ", km:"ចិត្តល្អ" }],
    mnemonic:{ vi:"-NESS = business, trang thai cua tinh chat do!", th:"-NESS = business สภาวะของคุณสมบัติ!", zh:"-NESS = business，某特质的状态!", ru:"-NESS = состояние качества!", lo:"-NESS = business ສະພາບ!", km:"-NESS = business ស្ថានភាព!" }},
  { id:"s-ous", affix:"-ous / -ious", type:"suffix", color:"#7E57C2",
    meaning:"having the quality of, full of",
    translations:{ vi:"có tính chất, đầy", th:"มีคุณสมบัติของ, เต็มไปด้วย", zh:"具有...性质，充满", ru:"имеющий качество, полный", lo:"ມີຄຸນສົມບັດ, ເຕັມ", km:"មានលក្ខណៈ ពោរពេញ" },
    examples:[{ word:"dangerous", vi:"nguy hiểm", th:"อันตราย", zh:"危险的", ru:"опасный", lo:"ອັນຕະລາຍ", km:"គ្រោះថ្នាក់" }, { word:"curious", vi:"tò mò", th:"อยากรู้", zh:"好奇的", ru:"любопытный", lo:"ຢາກຮູ້", km:"ចង់ដឹង" }, { word:"glorious", vi:"huy hoàng", th:"รุ่งโรจน์", zh:"光荣的", ru:"великолепный", lo:"ຮຸ່ງໂຮຈ", km:"ភ្លឺ" }],
    mnemonic:{ vi:"-OUS = famous, CO DAC DIEM hoac DAY TRAN!", th:"-OUS = famous มีคุณสมบัตินั้น!", zh:"-OUS = famous，具有某种特质!", ru:"-OUS = famous, известный!", lo:"-OUS = famous ມີ!", km:"-OUS = famous មានលក្ខណៈ!" }},
];
