// ROOT WORDS DICTIONARY — multi-language
// translations: vi / th / zh / ru / lo / km (en is `meaning`)

export const ROOT_WORDS = [
  { id:"aud", root:"aud / audi", meaning:"hear", color:"#FF6B6B", origin:"Latin: audire",
    translations:{ vi:"nghe", th:"ได้ยิน", zh:"听", ru:"слышать", lo:"ໄດ້ຍິນ", km:"ឮ" },
    examples:[
      { word:"audio",      vi:"âm thanh",        th:"เสียง",     zh:"音频",     ru:"аудио",        lo:"ສຽງ",       km:"សំឡេង" },
      { word:"auditorium", vi:"hội trường",       th:"ห้องประชุม",zh:"礼堂",     ru:"аудитория",    lo:"ຫ້ອງປະຊຸມ", km:"ផ្ទះប្រជុំ" },
      { word:"audible",    vi:"nghe được",        th:"ได้ยิน",    zh:"听得见的",  ru:"слышимый",     lo:"ໄດ້ຍິນໄດ້", km:"ឮបាន" },
      { word:"audience",   vi:"khán giả",         th:"ผู้ชม",     zh:"观众",     ru:"аудитория",    lo:"ຜູ້ຊົມ",    km:"អ្នកទស្សនា" },
      { word:"inaudible",  vi:"không nghe được",  th:"ไม่ได้ยิน", zh:"听不见的",  ru:"неслышимый",   lo:"ໄດ້ຍິນບໍ່ໄດ້",km:"ឮមិនបាន" },
    ]},
  { id:"bio", root:"bio", meaning:"life", color:"#4CAF50", origin:"Greek: bios",
    translations:{ vi:"sự sống, cuộc sống", th:"ชีวิต", zh:"生命", ru:"жизнь", lo:"ຊີວິດ", km:"ជីវិត" },
    examples:[
      { word:"biology",     vi:"sinh học",          th:"ชีววิทยา",                       zh:"生物学",   ru:"биология",        lo:"ຊີວະວິທະຍາ",            km:"ជីវវិទ្យា" },
      { word:"biography",   vi:"tiểu sử",           th:"ชีวประวัติ",                     zh:"传记",     ru:"биография",       lo:"ຊີວະປະຫວັດ",            km:"ជីវប្រវត្តិ" },
      { word:"biodiversity",vi:"đa dạng sinh học",  th:"ความหลากหลายทางชีวภาพ",          zh:"生物多样性",ru:"биоразнообразие",  lo:"ຄວາມຫລາກຫລາຍທາງຊີວະ",  km:"ជីវវ័ន្ដភាព" },
      { word:"antibiotics", vi:"kháng sinh",        th:"ยาปฏิชีวนะ",                     zh:"抗生素",   ru:"антибиотики",      lo:"ຢາຕ້ານເຊື້ອ",            km:"ថ្នាំប្រឆាំងមេរោគ" },
      { word:"biosphere",   vi:"sinh quyển",        th:"ชีวมณฑล",                       zh:"生物圈",   ru:"биосфера",         lo:"ຊີວາລຸຍ",               km:"ជីវមណ្ឌល" },
    ]},
  { id:"chron", root:"chron / chrono", meaning:"time", color:"#FF9800", origin:"Greek: khronos",
    translations:{ vi:"thời gian", th:"เวลา", zh:"时间", ru:"время", lo:"ເວລາ", km:"ពេលវេលា" },
    examples:[
      { word:"chronology",  vi:"niên đại học",  th:"ลำดับเวลา",   zh:"年代学",   ru:"хронология",      lo:"ລຳດັບເວລາ",  km:"ល្វែងពេលវេលា" },
      { word:"chronicle",   vi:"biên niên sử",  th:"พงศาวดาร",    zh:"编年史",   ru:"летопись",         lo:"ບົດບັນທຶກ",  km:"ប្រវត្តិ" },
      { word:"synchronize", vi:"đồng bộ hóa",   th:"ซิงโครไนซ์",  zh:"同步",     ru:"синхронизировать", lo:"ຕາມຈັງຫວະ", km:"ធ្វើសមកាល" },
      { word:"anachronism", vi:"sự lỗi thời",   th:"ความล้าสมัย", zh:"时代错误",  ru:"анахронизм",       lo:"ລ້າສະໄໝ",   km:"ភាពហួសសម័យ" },
      { word:"chronic",     vi:"mãn tính",      th:"เรื้อรัง",    zh:"慢性的",   ru:"хронический",      lo:"ຊຳເຮື້ອ",   km:"រ៉ាំរ៉ៃ" },
    ]},
  { id:"dict", root:"dict / dic", meaning:"say, speak", color:"#9C27B0", origin:"Latin: dicere",
    translations:{ vi:"nói, phát biểu", th:"พูด", zh:"说、讲", ru:"говорить", lo:"ເວົ້າ", km:"និយាយ" },
    examples:[
      { word:"dictionary", vi:"từ điển",       th:"พจนานุกรม",  zh:"词典",   ru:"словарь",         lo:"ວັດຈະນານຸກົມ",km:"វចនានុក្រម" },
      { word:"dictate",    vi:"đọc chính tả",  th:"บอกเล่า",    zh:"口述",   ru:"диктовать",       lo:"ກ່າວ",        km:"កំណត់" },
      { word:"predict",    vi:"dự đoán",       th:"ทำนาย",      zh:"预测",   ru:"предсказывать",   lo:"ທຳນາຍ",       km:"ព្យាករណ៍" },
      { word:"contradict", vi:"mâu thuẫn",     th:"ขัดแย้ง",    zh:"矛盾",   ru:"противоречить",   lo:"ຂັດແຍ້ງ",     km:"ផ្ទុយគ្នា" },
      { word:"verdict",    vi:"phán quyết",    th:"คำพิพากษา",  zh:"裁决",   ru:"вердикт",         lo:"ຄຳຕັດສິນ",    km:"សាលក្រម" },
    ]},
  { id:"geo", root:"geo", meaning:"earth", color:"#8BC34A", origin:"Greek: gê",
    translations:{ vi:"trái đất, địa lý", th:"โลก, ดิน", zh:"地球、地理", ru:"земля", lo:"ໂລກ, ດິນ", km:"ផែនដី" },
    examples:[
      { word:"geography",  vi:"địa lý",          th:"ภูมิศาสตร์",         zh:"地理",    ru:"география",   lo:"ພູມສາດ",          km:"ភូមិសាស្ត្រ" },
      { word:"geology",    vi:"địa chất học",    th:"ธรณีวิทยา",          zh:"地质学",  ru:"геология",    lo:"ທໍລະນີວິທະຍາ",    km:"ភូតគីវិទ្យា" },
      { word:"geometry",   vi:"hình học",        th:"เรขาคณิต",           zh:"几何",    ru:"геометрия",   lo:"ເລຂາຄະນິດ",       km:"រាងគណិត" },
      { word:"geopolitics",vi:"địa chính trị",   th:"ภูมิรัฐศาสตร์",     zh:"地缘政治",ru:"геополитика", lo:"ພູມລັດຖະສາດ",     km:"ភូមិនយោបាយ" },
      { word:"geothermal", vi:"địa nhiệt",       th:"ความร้อนใต้พิภพ",   zh:"地热",    ru:"геотермальный",lo:"ຄວາມຮ້ອນໃຕ້ດິນ",  km:"ភូមិកំដៅ" },
    ]},
  { id:"graph", root:"graph / gram", meaning:"write, draw, record", color:"#607D8B", origin:"Greek: graphein",
    translations:{ vi:"viết, vẽ, ghi chép", th:"เขียน, วาด", zh:"写、画、记录", ru:"писать, рисовать", lo:"ຂຽນ, ແຕ້ມ", km:"សរសេរ ឬគូរ" },
    examples:[
      { word:"photograph", vi:"ảnh chụp",  th:"ถ่ายภาพ",   zh:"照片",    ru:"фотография", lo:"ຮູບຖ່າຍ",    km:"រូបថត" },
      { word:"biography",  vi:"tiểu sử",  th:"ชีวประวัติ",zh:"传记",    ru:"биография",  lo:"ຊີວະປະຫວັດ",km:"ជីវប្រវត្តិ" },
      { word:"diagram",    vi:"sơ đồ",    th:"แผนภาพ",    zh:"图表",    ru:"диаграмма",  lo:"ແຜນຜັງ",     km:"គំនូស" },
      { word:"telegram",   vi:"điện tín", th:"โทรเลข",    zh:"电报",    ru:"телеграмма", lo:"ໂທລະເລກ",    km:"ទូរលេខ" },
      { word:"autograph",  vi:"chữ ký",   th:"ลายเซ็น",   zh:"亲笔签名",ru:"автограф",   lo:"ລາຍເຊັນ",    km:"ហត្ថប័ត" },
    ]},
  { id:"log", root:"log / logy", meaning:"word, study, reason", color:"#E91E63", origin:"Greek: logos",
    translations:{ vi:"lời nói, nghiên cứu, lý luận", th:"คำ, การศึกษา", zh:"词语、研究、推理", ru:"слово, наука", lo:"ຄຳ, ການສຶກສາ", km:"ពាក្យ ការសិក្សា" },
    examples:[
      { word:"biology",   vi:"sinh học",     th:"ชีววิทยา", zh:"生物学", ru:"биология",   lo:"ຊີວະວິທະຍາ",  km:"ជីវវិទ្យា" },
      { word:"psychology",vi:"tâm lý học",   th:"จิตวิทยา", zh:"心理学", ru:"психология", lo:"ຈິດຕະວິທະຍາ", km:"ចិត្តវិទ្យា" },
      { word:"dialogue",  vi:"đối thoại",    th:"บทสนทนา",  zh:"对话",   ru:"диалог",     lo:"ການສົນທະນາ",  km:"ការសន្ទនា" },
      { word:"logic",     vi:"logic, lý luận",th:"ตรรกะ",   zh:"逻辑",   ru:"логика",     lo:"ຕັກກະ",       km:"តក្ក" },
      { word:"catalog",   vi:"danh mục",     th:"แค็ตตาล็อก",zh:"目录", ru:"каталог",    lo:"ລາຍການ",      km:"សៀវភៅបញ្ជី" },
    ]},
  { id:"port", root:"port", meaning:"carry", color:"#795548", origin:"Latin: portare",
    translations:{ vi:"mang, vận chuyển", th:"ถือ, ขนส่ง", zh:"携带、运输", ru:"нести, переносить", lo:"ຖື, ຂົນສົ່ງ", km:"ដឹក" },
    examples:[
      { word:"transport",vi:"vận chuyển", th:"ขนส่ง",     zh:"运输",   ru:"транспорт",  lo:"ຂົນສົ່ງ", km:"ដឹកជញ្ជូន" },
      { word:"import",   vi:"nhập khẩu", th:"นำเข้า",    zh:"进口",   ru:"импорт",     lo:"ນຳເຂົ້າ", km:"នាំចូល" },
      { word:"export",   vi:"xuất khẩu", th:"ส่งออก",    zh:"出口",   ru:"экспорт",    lo:"ສົ່ງອອກ", km:"នាំចេញ" },
      { word:"portable", vi:"di động",   th:"พกพาได้",   zh:"便携的",  ru:"переносной", lo:"ຖືໄດ້",   km:"ចល័ត" },
      { word:"report",   vi:"báo cáo",   th:"รายงาน",    zh:"报告",   ru:"доклад",     lo:"ລາຍງານ",  km:"របាយការណ៍" },
    ]},
  { id:"scrib", root:"scrib / script", meaning:"write", color:"#F44336", origin:"Latin: scribere",
    translations:{ vi:"viết", th:"เขียน", zh:"写", ru:"писать", lo:"ຂຽນ", km:"សរសេរ" },
    examples:[
      { word:"describe",  vi:"mô tả",      th:"บรรยาย",     zh:"描述",  ru:"описывать",      lo:"ອະທິບາຍ",  km:"ពិពណ៌នា" },
      { word:"subscribe", vi:"đăng ký",    th:"สมัครสมาชิก",zh:"订阅",  ru:"подписываться",  lo:"ສະໝັກ",    km:"ចុះឈ្មោះ" },
      { word:"manuscript",vi:"bản thảo",   th:"ต้นฉบับ",    zh:"手稿",  ru:"рукопись",       lo:"ຕົ້ນສະບັບ",km:"ព្រឹត្តិបត្រ" },
      { word:"scripture", vi:"kinh sách",  th:"พระคัมภีร์", zh:"圣典",  ru:"священное писание",lo:"ຄຳພີ",    km:"គម្ពីរ" },
      { word:"prescribe", vi:"kê đơn",     th:"สั่งยา",     zh:"开处方",ru:"предписывать",   lo:"ສັ່ງຢາ",   km:"ចេញវេជ្ជបញ្ជា" },
    ]},
  { id:"spec", root:"spec / spect", meaning:"see, look", color:"#673AB7", origin:"Latin: specere",
    translations:{ vi:"nhìn, xem", th:"ดู, มอง", zh:"看、观察", ru:"смотреть, видеть", lo:"ເບິ່ງ, ແນ", km:"មើល" },
    examples:[
      { word:"inspect",    vi:"kiểm tra",   th:"ตรวจสอบ",             zh:"检查",   ru:"инспектировать", lo:"ກວດສອບ",   km:"ត្រួតពិនិត្យ" },
      { word:"spectator",  vi:"khán giả",   th:"ผู้ชม",               zh:"观众",   ru:"зритель",        lo:"ຜູ້ຊົມ",   km:"អ្នកទស្សនា" },
      { word:"spectacular",vi:"ngoạn mục",  th:"น่าตื่นตาตื่นใจ",     zh:"壮观",   ru:"зрелищный",      lo:"ໜ້າຕື່ນໃຈ",km:"អស្ចារ្យ" },
      { word:"perspective",vi:"quan điểm",  th:"มุมมอง",              zh:"观点",   ru:"перспектива",    lo:"ທັດສະນະ",  km:"ទស្សនៈ" },
      { word:"spectrum",   vi:"quang phổ",  th:"สเปกตรัม",            zh:"光谱",   ru:"спектр",         lo:"ຄ່າຕ່ອມ",  km:"វណ្ណដ្ឋ" },
    ]},
  { id:"struct", root:"struct / stru", meaning:"build", color:"#FF9800", origin:"Latin: struere",
    translations:{ vi:"xây dựng", th:"สร้าง", zh:"建造", ru:"строить", lo:"ກໍ່ສ້າງ", km:"សាងសង់" },
    examples:[
      { word:"construct", vi:"xây dựng",  th:"ก่อสร้าง",  zh:"建造",  ru:"строить",          lo:"ກໍ່ສ້າງ",  km:"សាងសង់" },
      { word:"structure", vi:"cấu trúc",  th:"โครงสร้าง", zh:"结构",  ru:"структура",        lo:"ໂຄງສ້າງ",  km:"រចនាសម្ព័ន្ធ" },
      { word:"destroy",   vi:"phá hủy",   th:"ทำลาย",     zh:"毁坏",  ru:"разрушать",        lo:"ທຳລາຍ",    km:"បំផ្លាញ" },
      { word:"instruct",  vi:"hướng dẫn", th:"สอน",       zh:"指导",  ru:"инструктировать",  lo:"ສອນ",      km:"ណែនាំ" },
      { word:"obstruct",  vi:"cản trở",   th:"ขัดขวาง",   zh:"阻碍",  ru:"препятствовать",   lo:"ຂັດຂວາງ",  km:"រាំងស្ទះ" },
    ]},
  { id:"vid", root:"vid / vis", meaning:"see", color:"#F06292", origin:"Latin: videre",
    translations:{ vi:"nhìn thấy", th:"มองเห็น", zh:"看见", ru:"видеть", lo:"ເຫັນ", km:"ឃើញ" },
    examples:[
      { word:"video",    vi:"video",              th:"วิดีโอ",     zh:"视频",   ru:"видео",            lo:"ວີດີໂອ",   km:"វីដេអូ" },
      { word:"visible",  vi:"có thể nhìn thấy",   th:"มองเห็นได้", zh:"可见的", ru:"видимый",          lo:"ເຫັນໄດ້",  km:"មើលឃើញ" },
      { word:"vision",   vi:"tầm nhìn / thị giác",th:"วิสัยทัศน์", zh:"视觉",   ru:"видение",          lo:"ວິໄສທັດ",  km:"ចក្ខុវិស័យ" },
      { word:"evidence", vi:"bằng chứng",         th:"หลักฐาน",    zh:"证据",   ru:"доказательство",   lo:"ຫຼັກຖານ",  km:"ភស្តុតាង" },
      { word:"supervise",vi:"giám sát",           th:"กำกับดูแล",  zh:"监督",   ru:"контролировать",   lo:"ກວດກາ",    km:"ត្រួតពិនិត្យ" },
    ]},
  { id:"voc", root:"voc / vok", meaning:"voice, call", color:"#AB47BC", origin:"Latin: vox/vocare",
    translations:{ vi:"giọng nói, gọi", th:"เสียง, เรียก", zh:"声音、呼叫", ru:"голос, звать", lo:"ສຽງ, ຮຽກ", km:"សំឡេង ការហៅ" },
    examples:[
      { word:"vocabulary",vi:"từ vựng",    th:"คำศัพท์",   zh:"词汇",   ru:"словарный запас", lo:"ຄຳສັບ",           km:"សព្ទ" },
      { word:"vocal",     vi:"giọng nói",  th:"เสียงร้อง", zh:"声乐的", ru:"вокальный",       lo:"ທາງສຽງ",          km:"សំឡេង" },
      { word:"provoke",   vi:"khiêu khích",th:"ยั่วยุ",    zh:"激怒",   ru:"провоцировать",   lo:"ຍຸງ",             km:"បង្កហេតុ" },
      { word:"advocate",  vi:"ủng hộ",     th:"สนับสนุน",  zh:"倡导",   ru:"защитник",        lo:"ສະໜັບສະໜຸນ",      km:"គាំទ្រ" },
      { word:"invoke",    vi:"kêu gọi",    th:"เรียกหา",   zh:"唤起",   ru:"взывать",         lo:"ຮຽກຮ້ອງ",         km:"ហៅ" },
    ]},
  { id:"vert", root:"vert / vers", meaning:"turn", color:"#26C6DA", origin:"Latin: vertere",
    translations:{ vi:"quay, xoay", th:"หมุน, เปลี่ยน", zh:"转动、变化", ru:"повернуть", lo:"ໝູນ, ປ່ຽນ", km:"បង្វិល" },
    examples:[
      { word:"convert",   vi:"chuyển đổi",   th:"แปลง",     zh:"转换",    ru:"конвертировать", lo:"ປ່ຽນ",    km:"បំប្លែង" },
      { word:"reverse",   vi:"đảo ngược",    th:"ย้อนกลับ", zh:"逆转",    ru:"обратный",       lo:"ກັບຄືນ",  km:"បញ្ច្រាស" },
      { word:"divert",    vi:"chuyển hướng", th:"เบี่ยงเบน", zh:"转移",    ru:"отклонять",      lo:"ປ່ຽນທິດ", km:"ងាកចេញ" },
      { word:"versatile", vi:"linh hoạt",    th:"หลากหลาย", zh:"多才多艺", ru:"универсальный",  lo:"ຫຼາກຫຼາຍ",km:"ពហុភាព" },
      { word:"universe",  vi:"vũ trụ",       th:"จักรวาล",  zh:"宇宙",    ru:"вселенная",      lo:"ຈັກກະວານ",km:"សកលលោក" },
    ]},
  { id:"mit", root:"mit / miss", meaning:"send", color:"#3F51B5", origin:"Latin: mittere",
    translations:{ vi:"gửi, phát", th:"ส่ง", zh:"发送", ru:"посылать", lo:"ສົ່ງ", km:"ផ្ញើ" },
    examples:[
      { word:"transmit", vi:"truyền đi", th:"ส่งผ่าน",   zh:"传输",  ru:"передавать",    lo:"ສົ່ງຕໍ່",km:"បញ្ជូន" },
      { word:"mission",  vi:"sứ mệnh",  th:"ภารกิจ",    zh:"使命",  ru:"миссия",        lo:"ພາລະກິດ",km:"បេសកម្ម" },
      { word:"submit",   vi:"nộp, gửi", th:"ส่ง",       zh:"提交",  ru:"подавать",      lo:"ສົ່ງ",   km:"ដាក់ស្នើ" },
      { word:"dismiss",  vi:"sa thải",  th:"ไล่ออก",    zh:"解雇",  ru:"увольнять",     lo:"ໄລ່ອອກ", km:"បណ្តេញ" },
      { word:"emit",     vi:"phát ra",  th:"ปล่อยออก",  zh:"发出",  ru:"излучать",      lo:"ປ່ອຍ",   km:"បំភាយ" },
    ]},
  { id:"phon", root:"phon / phone", meaning:"sound, voice", color:"#009688", origin:"Greek: phone",
    translations:{ vi:"âm thanh, giọng nói", th:"เสียง", zh:"声音", ru:"звук, голос", lo:"ສຽງ", km:"សំឡេង" },
    examples:[
      { word:"telephone",  vi:"điện thoại", th:"โทรศัพท์",  zh:"电话",   ru:"телефон",  lo:"ໂທລະສັບ",    km:"ទូរស័ព្ទ" },
      { word:"microphone", vi:"micrô",      th:"ไมโครโฟน",  zh:"麦克风",  ru:"микрофон", lo:"ໄມໂຄຣໂຟນ",   km:"មីក្រូហ្វូន" },
      { word:"phonics",    vi:"ngữ âm học", th:"โฟนิกส์",   zh:"拼音法",  ru:"фоника",   lo:"ສຽງສາດ",      km:"សូរ" },
      { word:"symphony",   vi:"giao hưởng", th:"ซิมโฟนี",   zh:"交响乐",  ru:"симфония",  lo:"ຊິມໂຟນີ",     km:"ស៊ីំហ្វូនី" },
      { word:"saxophone",  vi:"kèn saxophone",th:"แซกโซโฟน",zh:"萨克斯",  ru:"саксофон", lo:"ແຊັກໂຊໂຟນ",  km:"សាក់ស្ហ្វូន" },
    ]},
  { id:"gen", root:"gen / gene", meaning:"birth, origin, race", color:"#00BCD4", origin:"Greek/Latin: genos/genus",
    translations:{ vi:"nguồn gốc, sinh ra", th:"กำเนิด, เชื้อชาติ", zh:"出生、起源", ru:"рождение, происхождение", lo:"ກຳເນີດ, ເຊື້ອຊາດ", km:"ដើមកំណើត" },
    examples:[
      { word:"generate",  vi:"tạo ra",     th:"สร้าง",     zh:"生成",   ru:"генерировать", lo:"ສ້າງ",     km:"បង្កើត" },
      { word:"genetics",  vi:"di truyền",  th:"พันธุกรรม", zh:"遗传学",  ru:"генетика",     lo:"ກຳມະພັນ",  km:"ហ្សែន" },
      { word:"indigenous",vi:"bản địa",    th:"พื้นเมือง", zh:"土著的",  ru:"коренной",     lo:"ພື້ນເມືອງ",km:"ជនជាតិដើម" },
      { word:"generous",  vi:"rộng lượng", th:"ใจดี",      zh:"慷慨的",  ru:"щедрый",       lo:"ໃຈດີ",     km:"មានចិត្ត" },
      { word:"genre",     vi:"thể loại",   th:"ประเภท",    zh:"类型",   ru:"жанр",         lo:"ປະເພດ",    km:"ប្រភេទ" },
    ]},
];
